#!/bin/bash
# =============================================================================
# Oracle StatsPack Report 2 HTML  (c) 2003-2004 by IzzySoft (devel@izzysoft.de)
# -----------------------------------------------------------------------------
# $Id$
# -----------------------------------------------------------------------------
# This Shell Script is the configuration file of OSPRep - and the only one the
# user has to edit. Only change the other files if you exactly know what you
# are doing!
# =============================================================================

# -----------------------------------------------------------------[ Files ]---
# directory to store temporary files in
TMPDIR=/tmp
# in which directory should the report ($ORACLE_SID.html) be placed
REPDIR=/var/www/html/oracle/statspack
# StyleSheet to use
CSS=../main.css

# --------------------------------------------------------------[ DataBase ]---
# SID of the database to analyse
export ORACLE_SID=$1
# login information
user=perfstat
password="pyha#"

# -------------------------------------------------------------------[ SQL ]---
# Top settings: Display Top N Statements
TOP_N_SQL=5
TOP_N_WAITS=10

# Exclusion of performance stats for these object owners (where possible).
# Comment this statement out if you want to exclude nobody. Case sensitive!
EXC_PERF_FOR="SYS SYSTEM"

#--- SnapShot Interval. Set values to 0 for automatic evaluation of latest
#--- continuous interval (i.e. the interval ending with the latest recording
#--- SnapShot and starting with the first SnapShot having the same database
#--- startup time)
#--- You may set both values to 0 (last interval will be used then), both to
#--- a value > 0 (specified value is used), or START_ID=0 and END_ID>0. In
#--- all cases, only specify existing SnapShot IDs.
#--- Arguments on the command line override these settings.
START_ID=0
END_ID=0

# --------------------------------------------------------------[ Features ]---
# Include All Waits? [0|1]
MK_ALLWAITS=0
# Include Background Waits? [0|1]
MK_BGWAITS=0
# Include Instance Activity? [0|1]
MK_INSTACT=0
# Include Undo Segment _Statistics_? [0|1]
MK_USSTAT=0
# Include Latch Activity? [0|1]
MK_LACT=0
# Include Latch Miss Sources (only needed and understood by Oracle staff) [0|1]
# If MK_LACT=0 it will never be included.
MK_LMS=0
# Include init.ora parameter changes? [0|1]
MK_IORA=1
# Include SGA Summary and BreakDown stats? [0|1]
# If MK_SGASUM=0, SGABREAK is excluded automatically
MK_SGASUM=1
MK_SGABREAK=0
# Create the statistics for DictionaryCache and LibraryCache? [0|1]
MK_DC=1
MK_LC=1
# Include Rollback Segment Stats & Storage? [0|1]
MK_RSSTAT=0
MK_RSSTOR=0

# -------------------------------------------------------------[ Go4Colors ]---
# WR_* stands for WarnRatio, AR_* for AlertRatio. The next letters indicate the
# report segment: *_IE_* is Instance Efficiency, *_TS_* Table Space & FileIO
# Summary, *_EP_* is execution plans, *_DF_* Datafiles Statistics, *_LC_*
# Library Cache. For more details, see the HTML documentation.
WR_IE_BUFFNW=80
AR_IE_BUFFNW=60
WR_IE_REDONW=90
AR_IE_REDONW=75
WR_IE_BUFFHIT=50
AR_IE_BUFFHIT=30
WR_IE_IMSORT=85
AR_IE_IMSORT=70
WR_IE_LIBHIT=80
AR_IE_LIBHIT=60
WR_IE_SOFTPRS=80
AR_IE_SOFTPRS=60
WR_IE_PRSC2E=80
AR_IE_PRSC2E=60
WR_IE_LAHIT=85
AR_IE_LAHIT=70
# Full Table Scans will always issue a warning in the execution plans, so there
# is no WR_* value here
AR_EP_FTS=1000
WR_DF_CHNG=50
AR_DF_CHNG=100
WR_TS_BLKRD=80
AR_TS_BLKRD=100
WR_TS_RD=50
AR_TS_RD=80
WR_LC_MISS=15
AR_LC_MISS=40
WR_LC_RLPRQ=10
AR_LC_RLPRQ=30
WR_LC_INVPRQ=10
AR_LC_INVPRQ=20
# ===================================================================[ EOF ]===
